# Generated by Django 6.1 on 2026-09-24 08:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sitebanner_systemsetting'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('system', 'System Default'), ('light', 'Light'), ('dark', 'Dark')], default='system', max_length=10)),
                ('currency', models.CharField(choices=[('USD', 'USD ($)'), ('EUR', 'EUR (€)'), ('GBP', 'GBP (£)'), ('MXN', 'MXN ($)'), ('CAD', 'CAD ($)')], default='USD', max_length=3)),
                ('dashboard_period', models.CharField(choices=[('month', 'This Month'), ('30days', 'Last 30 Days'), ('year', 'This Year')], default='month', max_length=10)),
                ('default_transaction_type', models.CharField(choices=[('expense', 'Expense'), ('income', 'Income')], default='expense', max_length=10)),
                ('items_per_page', models.PositiveIntegerField(default=25)),
                ('budget_warning_threshold', models.PositiveIntegerField(default=80)),
                ('hide_financial_amounts', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
