# Generated by Django 6.1 on 2026-09-24 08:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_usersettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='student_mode',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='week_start',
            field=models.CharField(choices=[('sunday', 'Sunday'), ('monday', 'Monday')], default='sunday', max_length=10),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD ($)'), ('MXN', 'MXN ($)'), ('EUR', 'EUR (€)'), ('GBP', 'GBP (£)'), ('CAD', 'CAD ($)')], default='USD', max_length=3),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='expense_settings', to=settings.AUTH_USER_MODEL),
        ),
    ]
